### ISSUE TITLE
The names randomly keep disappearing

### ISSUE THREAD

**Issue by bumbu** [9-volt/Words-Frequency-Visualization#6]
![screen shot 2014-04-24 at 16 00 59](https://cloud.githubusercontent.com/assets/1770364/2789635/80394f0e-cbb0-11e3-86af-bd7a1819e743.png)

Previously reported 9-volt/press-kit#9

**Comment by bumbu** [comment]
@minivan do you have a strategy how to reproduce this? I saw this behaviour few times, but it seemed to be random and right now I can't reproduce that.

**Comment by bumbu** [comment]
May be reproduced by clicking on a circle, switching tabs and going back.

It seems to be [an issue](https://code.google.com/p/chromium/issues/detail?id=336476) in Chrome 34 that was fixed in Chrome 35 (didn't test).
Chrome 33 works ok (after updating to 34 it breaks).
Chrome 36 on the same machine works ok.
Firefox works ok.
Opera 20 works ok (same Blink as in Chromium 33) but may get the same bug on next update to the same layout engine that is now in Chrome 34.

Text visibility may be restored by assigning a class to the text element with following declaration

``` css
.classes-affected-by-issue
{
    -webkit-animation-duration: 0.1s;
    -webkit-animation-name: fontfix;
    -webkit-animation-iteration-count: 1;
    -webkit-animation-timing-function: linear;
    -webkit-animation-delay: 0.1s;
}

@-webkit-keyframes fontfix{
    from{   opacity: 1; }
    to{ opacity: 1; }
}
```

or changing display attribute with intermediate forced refresh

``` js
sel.style.display='none';
sel.offsetHeight;
sel.style.display='block';
```

but these fixes should be reapplied each time user switches tabs
